# Generated by Django 4.0.2 on 2022-02-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='transction_id',
            new_name='transaction_id',
        ),
    ]
